/*
 * HAWKORE CONFIDENTIAL
 * ____________________
 *
 * 2019 (c) HAWKORE, S.L. All Rights Reserved.
 *
 * NOTICE: All information contained herein is, and remains
 * the property of HAWKORE, S.L and its suppliers,
 * if any. The intellectual and technical concepts contained
 * herein are proprietary to HAWKORE, S.L. and its suppliers
 * and may be covered by OEPM or EPO, and are protected
 * by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from HAWKORE, S.L.
 */
package com.hawkore.mule.extensions.sap.internal.factory.constants;

import com.hawkore.mule.extensions.sap.internal.SapJCoExtension;

/**
 * Xml schema constants.
 *
 * @author Alex Alsina de la Torre (alex.alsina@mango.com)
 */
public final class XmlSchemaConstants {

    private XmlSchemaConstants() {}

    /**
     * The constant VERSION_ATTR.
     */
    public static final String VERSION_ATTR = "version";
    /**
     * The constant VERSION_1_0.
     */
    public static final String VERSION_1_0 = "1.0";
    /**
     * The constant APP_INFO.
     */
    public static final String APP_INFO = "Generated by SAP JCo connector for Mule 4. 2019 (c) "
                                              + SapJCoExtension.VENDOR + " All Rights Reserved";
    /**
     * The constant UTF_8.
     */
    public static final String UTF_8 = "UTF-8";
    /**
     * The constant XSD_SCHEMA.
     */
    public static final String XSD_SCHEMA = "xsd:schema";
    /**
     * The constant ENCODING.
     */
    public static final String ENCODING = "encoding";
    /**
     * The constant OMIT_XML_DECLARATION.
     */
    public static final String OMIT_XML_DECLARATION = "omit-xml-declaration";
    /**
     * The constant INDENT.
     */
    public static final String INDENT = "indent";
    /**
     * The constant METHOD.
     */
    public static final String METHOD = "method";
    /**
     * The constant VALUE_NO.
     */
    public static final String VALUE_NO = "no";
    /**
     * The constant VALUE_YES.
     */
    public static final String VALUE_YES = "yes";
    /**
     * The constant VALUE_REQUIRED.
     */
    public static final String VALUE_REQUIRED = "required";
    /**
     * The constant XML.
     */
    public static final String XML = "xml";
    /**
     * The constant XSD_ELEMENT.
     */
    public static final String XSD_ELEMENT = "xsd:element";
    /**
     * The constant NAME_ATTR.
     */
    public static final String NAME_ATTR = "name";
    /**
     * The constant USE_ATTR.
     */
    public static final String USE_ATTR = "use";
    /**
     * The constant MIN_OCCURS_ATTR.
     */
    public static final String MIN_OCCURS_ATTR = "minOccurs";
    /**
     * The constant MAX_OCCURS_ATTR.
     */
    public static final String MAX_OCCURS_ATTR = "maxOccurs";
    /**
     * The constant VALUE_ONE.
     */
    public static final String VALUE_ONE = "1";
    /**
     * The constant VALUE_ZERO.
     */
    public static final String VALUE_ZERO = "0";
    /**
     * The constant XSD_SIMPLE_TYPE.
     */
    public static final String XSD_SIMPLE_TYPE = "xsd:simpleType";
    /**
     * The constant XSD_RESTRICTION.
     */
    public static final String XSD_RESTRICTION = "xsd:restriction";
    /**
     * The constant XSD_MAX_LENGTH.
     */
    public static final String XSD_MAX_LENGTH = "xsd:maxLength";
    /**
     * The constant VALUE_ATTR.
     */
    public static final String VALUE_ATTR = "value";
    /**
     * The constant XSD_STRING.
     */
    public static final String XSD_STRING = "xsd:string";
    /**
     * The constant XSD_COMPLEX_TYPE.
     */
    public static final String XSD_COMPLEX_TYPE = "xsd:complexType";
    /**
     * The constant XSD_SEQUENCE.
     */
    public static final String XSD_SEQUENCE = "xsd:sequence";
    /**
     * The constant XSD_ALL.
     */
    public static final String XSD_ALL = "xsd:all";
    /**
     * The constant XSD_ANNOTATION.
     */
    public static final String XSD_ANNOTATION = "xsd:annotation";
    /**
     * The constant XSD_APPINFO.
     */
    public static final String XSD_APPINFO = "xsd:appinfo";
    /**
     * The constant SOURCE_ATTR.
     */
    public static final String SOURCE_ATTR = "source";
    /**
     * The constant XSD_DOCUMENTATION.
     */
    public static final String XSD_DOCUMENTATION = "xsd:documentation";
    /**
     * The constant BASE_ATTR.
     */
    public static final String BASE_ATTR = "base";
    /**
     * The constant TYPE_ATTR.
     */
    public static final String TYPE_ATTR = "type";
    /**
     * The constant XSD_ATTRIBUTE.
     */
    public static final String XSD_ATTRIBUTE = "xsd:attribute";
    /**
     * The constant XSD_ENUMERATION.
     */
    public static final String XSD_ENUMERATION = "xsd:enumeration";

}
